# Generated by Django 4.2 on 2023-05-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.CharField(default=''),
        ),
    ]
